
export const commonTranslations = {
  ar: {
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    first_name: "الاسم الأول",
    surname: "اسم الأب (الشهرة)",
    last_name: "الاسم الأخير",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    address: "العنوان",
    city: "المدينة",
    area: "المنطقة",
    specialty: "التخصص",
    insurance: "التأمين",
    active: "نشط",
    inactive: "غير نشط",
    owner: "مالك",
    success: "نجاح",
    error: "خطأ",
    info: "معلومات",
    today: "اليوم",
    am: "صباحاً",
    pm: "مساءً",
    male: "ذكر",
    female: "أنثى",
    gender: "الجنس",
    birth_date: "تاريخ الميلاد",
    save_changes: "حفظ التغييرات",
    discard_changes: "تجاهل التغييرات",
    confirm_message: "هل أنت متأكد؟",
    yes: "نعم",
    no: "لا",
    status: "الحالة",
    role: "الدور",
    last_login: "آخر تسجيل دخول",
    join_date: "تاريخ الانضمام",
    user_id: "معرّف المستخدم",
    working_hours: "مواعيد العمل",
    edit_working_hours: "تعديل مواعيد العمل",
    working_days: "أيام العمل",
    days: "أيام",
    off_days: "أيام العطل",
    holiday: "عطلة",
    add_period: "إضافة فترة",
    from: "من",
    to: "إلى",
    change: "تغيير",
    save_clinic_success: "تم حفظ بيانات العيادة بنجاح",
    cancel_success: "تم إلغاء التغييرات",
    required_field: "هذا الحقل مطلوب",
    phone_number: "رقم الهاتف",
    clinic_name: "اسم العيادة",
    settings_saved: "تم حفظ الإعدادات بنجاح",
    settings_canceled: "تم إلغاء التغييرات بنجاح",
    fix_errors: "يرجى تصحيح الأخطاء قبل الحفظ",
  },
  en: {
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    first_name: "First Name",
    surname: "Surname",
    last_name: "Last Name",
    email: "Email",
    phone: "Phone Number",
    address: "Address",
    city: "City",
    area: "Area",
    specialty: "Specialty",
    insurance: "Insurance",
    active: "Active",
    inactive: "Inactive",
    owner: "Owner",
    success: "Success",
    error: "Error",
    info: "Info",
    today: "Today",
    am: "AM",
    pm: "PM",
    male: "Male",
    female: "Female",
    gender: "Gender",
    birth_date: "Date of Birth",
    save_changes: "Save Changes",
    discard_changes: "Discard Changes",
    confirm_message: "Are you sure?",
    yes: "Yes",
    no: "No",
    status: "Status",
    role: "Role",
    last_login: "Last Login",
    join_date: "Join Date",
    user_id: "User ID",
    working_hours: "Working Hours",
    edit_working_hours: "Edit Working Hours",
    working_days: "Working Days",
    days: "Days",
    off_days: "Off Days",
    holiday: "Holiday",
    add_period: "Add Period",
    from: "From",
    to: "To",
    change: "Change",
    save_clinic_success: "Clinic information saved successfully",
    cancel_success: "Changes canceled",
    required_field: "This field is required",
    phone_number: "Phone Number",
    clinic_name: "Clinic Name",
    settings_saved: "Settings saved successfully",
    settings_canceled: "Changes canceled successfully",
    fix_errors: "Please fix errors before saving",
  }
};
