export const initialDoctors = [
  {
    id: 1,
    first_name_ar: 'عمر',
    surname_ar: 'الزعبي',
    last_name_ar: 'الزعبي',
    first_name_en: 'Omar',
    surname_en: 'Al-Zoughbi',
    last_name_en: 'Al-Zoughbi',
    name_ar: 'د. عمر الزعبي',
    name_en: 'Dr. Omar Al-Zoughbi',
    specialty_ar: 'طب عام',
    specialty_en: 'General Medicine',
    status: 'active',
    phone: '0789651800',
    email: 'omar.Zoughbi@medexa.jo',
    patients: 145,
    revenue: '2400',
    initial_ar: 'ع',
    initial_en: 'O',
    gender_ar: 'ذكر',
    gender_en: 'Male',
    dob: '1985-05-15',
    description_ar: 'أخصائي طب عام بخبرة تزيد عن 10 سنوات في الرعاية الصحية الأولية والتشخيص.',
    description_en: 'General practitioner with over 10 years of experience in primary health care and diagnosis.',
    permissions: ['managePatients', 'manageAppointments', 'medicalRecords']
  },
  {
    id: 2,
    first_name_ar: 'ليلى',
    surname_ar: 'الخطيب',
    last_name_ar: 'الخطيب',
    first_name_en: 'Layla',
    surname_en: 'Al-Khatib',
    last_name_en: 'Al-Khatib',
    name_ar: 'د. ليلى الخطيب',
    name_en: 'Dr. Layla Al-Khatib',
    specialty_ar: 'أطفال',
    specialty_en: 'Pediatrics',
    status: 'active',
    phone: '0789651801',
    email: 'layla.khatib@medexa.jo',
    patients: 198,
    revenue: '3200',
    initial_ar: 'ل',
    initial_en: 'L',
    gender_ar: 'أنثى',
    gender_en: 'Female',
    dob: '1990-08-22',
    description_ar: 'استشارية طب أطفال متخصصة في النمو والتطور وتغذية الأطفال.',
    description_en: 'Pediatric consultant specialized in growth, development and child nutrition.',
    permissions: ['managePatients', 'manageAppointments', 'medicalRecords', 'financialReports']
  },
  {
    id: 3,
    first_name_ar: 'هند',
    surname_ar: 'الطراونة',
    last_name_ar: 'الطراونة',
    first_name_en: 'Hind',
    surname_en: 'Al-Tarawneh',
    last_name_en: 'Al-Tarawneh',
    name_ar: 'د. هند الطراونة',
    name_en: 'Dr. Hind Al-Tarawneh',
    specialty_ar: 'أسنان',
    specialty_en: 'Dentistry',
    status: 'active',
    phone: '0789651802',
    email: 'hind.tarawneh@medexa.jo',
    patients: 112,
    revenue: '1800',
    initial_ar: 'هـ',
    initial_en: 'H',
    gender_ar: 'أنثى',
    gender_en: 'Female',
    dob: '1988-03-10',
    description_ar: 'طبيبة أسنان متخصصة في تجميل الأسنان والتركيبات الثابتة والحشوات التجميلية.',
    description_en: 'Dentist specialized in cosmetic dentistry, fixed prosthodontics and cosmetic fillings.',
    permissions: ['managePatients', 'medicalRecords']
  },
  {
    id: 4,
    first_name_ar: 'سامي',
    surname_ar: 'القضاة',
    last_name_ar: 'القضاة',
    first_name_en: 'Sami',
    surname_en: 'Qudah',
    last_name_en: 'Qudah',
    name_ar: 'د. سامي القضاة',
    name_en: 'Dr. Sami Qudah',
    specialty_ar: 'باطني',
    specialty_en: 'Internal Medicine',
    status: 'active',
    phone: '0789651803',
    email: 'sami.qudah@medexa.jo',
    patients: 215,
    revenue: '4100',
    initial_ar: 'س',
    initial_en: 'S',
    gender_ar: 'ذكر',
    gender_en: 'Male',
    dob: '1979-11-20',
    description_ar: 'استشاري أمراض باطنية متخصص في إدارة الأمراض المزمنة وارتفاع ضغط الدم والسكري.',
    description_en: 'Internal medicine consultant specialized in managing chronic diseases, hypertension and diabetes.',
    permissions: ['managePatients', 'manageAppointments', 'medicalRecords', 'financialReports']
  }
];
