
export const navTranslations = {
  ar: {
    nav: {
      dashboard: "لوحة التحكم",
      doctors: "الأطباء",
      secretary: "السكرتارية",
      patients: "المرضى",
      appointments: "المواعيد",
      records: "السجلات الطبية",
      finance: "المالية",
      settings: "الإعدادات",
      profile: "الملف الشخصي",
      search: "بحث عن مريض بالاسم أو الرقم...",
      notifications: "التنبيهات",
      new_notif: "موعد جديد",
      new_notif_desc: "مريض محمد علي قام بحجز موعد جديد",
      reminder: "تذكير",
      reminder_desc: "يجب مراجعة التقارير الطبية المسائية",
      payment: "دفعة مالية",
      payment_desc: "تم استلام دفعة جديدة بقيمة {amount} دينار",
      view_all: "عرض كل التنبيهات",
      logout: "تسجيل الخروج",
      logout_confirm: "هل أنت متأكد من رغبتك في تسجيل الخروج من النظام؟",
      logout_success: "تم تسجيل الخروج بنجاح",
      clinic_name: "عيادة النور الطبية",
      minutes_ago: "منذ {n} دقائق",
      hour_ago: "منذ ساعة",
      hours_ago: "منذ {n} ساعات",
    }
  },
  en: {
    nav: {
      dashboard: "Dashboard",
      doctors: "Doctors",
      secretary: "Secretary",
      patients: "Patients",
      appointments: "Appointments",
      records: "Medical Records",
      finance: "Finance",
      settings: "Settings",
      profile: "Profile",
      search: "Search for a patient by name or number...",
      notifications: "Notifications",
      new_notif: "New Appointment",
      new_notif_desc: "Patient Mohammed Ali booked a new appointment",
      reminder: "Reminder",
      reminder_desc: "Evening medical reports need review",
      payment: "Payment",
      payment_desc: "Payment received: {amount} JOD",
      view_all: "View All Notifications",
      logout: "Logout",
      logout_confirm: "Are you sure you want to logout from the system?",
      logout_success: "Logged out successfully",
      clinic_name: "Al-Noor Medical Clinic",
      minutes_ago: "{n} minutes ago",
      hour_ago: "1 hour ago",
      hours_ago: "{n} hours ago",
    }
  }
};
