
export const profileTranslations = {
  ar: {
    profile: {
      profile: "الملف الشخصي",
      clinic_profile: "ملف العيادة",
      manage_profile: "إدارة المعلومات الشخصية ومعلومات العيادة",
      clinic_owner: "مالك العيادة",
      change_email: "تغيير البريد الإلكتروني",
      personal_info: "المعلومات الشخصية",
      account_info: "معلومات الحساب",
      update_photo: "تحديث صورة الملف الشخصي بنجاح",
      discard_change_q: "تجاهل التغيير؟",
      discard_confirm_msg: "هل أنت متأكد من تجاهل التغييرات؟",
      discard_btn: "نعم، تجاهل",
      clinic_name: "اسم العيادة",
      full_address: "العنوان الكامل",
      sunday: "الأحد",
      monday: "الاثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
      friday: "الجمعة",
      saturday: "السبت",
      clinic_info: "معلومات العيادة",
      specialty: "التخصص",
      insurance: "اسم التأمين",
      insurance_placeholder: "اسم شركة التأمين",
      city: "المدينة",
      area: "المنطقة",
      working_hours_note: "سيتم تطبيق هذه الأوقات على نظام المواعيد والحجز",
      jordan: "الأردن",
      clinic_saved: "تم حفظ بيانات العيادة بنجاح",
      general_saved: "تم حفظ البيانات العامة بنجاح",
      discard_changes: "تجاهل التغييرات",
      change_email_desc: "لأمان حسابك، يرجى إدخال البريد الجديد وتأكيد كلمة المرور",
      current_email: "البريد الإلكتروني الحالي",
      new_email: "البريد الإلكتروني الجديد",
      password: "كلمة المرور",
      password_note: "يرجى إدخال كلمة المرور الحالية لتأكيد التغيير",
      email_confirm_sent: "تم إرسال رابط التأكيد للبريد الجديد",
      security_note: "بعد تغيير البريد الإلكتروني، سيتم إرسال رابط تأكيد إلى البريد الجديد",
      confirm_change: "تأكيد التغيير",
      close: "إغلاق",
    }
  },
  en: {
    profile: {
      profile: "Profile",
      clinic_profile: "Clinic Profile",
      manage_profile: "Manage personal and clinic information",
      clinic_owner: "Clinic Owner",
      change_email: "Change Email",
      personal_info: "Personal Information",
      account_info: "Account Information",
      update_photo: "Profile photo updated successfully",
      discard_change_q: "Discard changes?",
      discard_confirm_msg: "Are you sure you want to discard changes?",
      discard_btn: "Yes, Discard",
      clinic_name: "Clinic Name",
      full_address: "Full Address",
      sunday: "Sunday",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      clinic_info: "Clinic Information",
      specialty: "Specialty",
      insurance: "Insurance Name",
      insurance_placeholder: "Insurance company name",
      city: "City",
      area: "Area",
      working_hours_note: "These times will be applied to the appointment and booking system",
      jordan: "Jordan",
      clinic_saved: "Clinic information saved successfully",
      general_saved: "General profile saved successfully",
      discard_changes: "Discard changes",
      change_email_desc: "For your security, please enter the new email and confirm your password",
      current_email: "Current Email",
      new_email: "New Email",
      password: "Password",
      password_note: "Please enter your current password to confirm the change",
      email_confirm_sent: "A confirmation link has been sent to the new email",
      security_note: "After changing the email, a confirmation link will be sent to the new email",
      confirm_change: "Confirm Change",
      close: "Close",
    }
  }
};
