export const initialSecretaries = [
  {
    id: 1,
    first_name_ar: 'فاطمة',
    surname_ar: 'محمد',
    last_name_ar: 'محمد',
    first_name_en: 'Fatima',
    surname_en: 'Mohammed',
    last_name_en: 'Mohammed',
    name_ar: 'فاطمة محمد',
    name_en: 'Fatima Mohammed',
    role_ar: 'سكرتيرة رئيسية',
    role_en: 'Head Secretary',
    status: 'active',
    phone: '0789651803',
    email: 'fatima@clinic.com',
    gender_ar: 'أنثى',
    gender_en: 'Female',
    dob: '1992-04-12',
    description_ar: 'سكرتيرة خبيرة في إدارة العيادات والمواعيد، تتحدث العربية والإنجليزية بطلاقة.',
    description_en: 'Experienced secretary in clinic management and appointments, fluent in Arabic and English.',
    permissions: ['managePatients', 'manageAppointments', 'medicalRecords']
  },
  {
    id: 2,
    first_name_ar: 'عمر',
    surname_ar: 'حسن',
    last_name_ar: 'حسن',
    first_name_en: 'Omar',
    surname_en: 'Hassan',
    last_name_en: 'Hassan',
    name_ar: 'عمر حسن',
    name_en: 'Omar Hassan',
    role_ar: 'استقبال',
    role_en: 'Receptionist',
    status: 'active',
    phone: '0789651804',
    email: 'omar@clinic.com',
    gender_ar: 'ذكر',
    gender_en: 'Male',
    dob: '1995-12-01',
    description_ar: 'موظف استقبال متميز، مسؤول عن تنظيم دخول المرضى والرد على الاستفسارات الهاتفية.',
    description_en: 'Distinguished receptionist, responsible for organizing patient entry and answering telephone inquiries.',
    permissions: ['manageAppointments']
  }
];
