
export const settingsTranslations = {
  ar: {
    settings: {
      settings: "إعدادات النظام",
      manage_settings: "إدارة إعدادات العيادة، أوقات العمل، والخيارات العامة",
      clinic_info: "معلومات العيادة",
      clinic_info_desc: "تحديث البيانات الأساسية للعيادة مثل الاسم، الهاتف، والعنوان",
      general_settings: "إعدادات عامة",
      general_settings_desc: "تعديل تفضيلات النظام، اللغة، والعملة الافتراضية",
      working_hours: "أوقات العمل",
      working_hours_desc: "تحديد فترات العمل اليومية لكل يوم من أيام الأسبوع",
      language: "اللغة",
      select_language: "اختر لغة النظام",
      arabic: "العربية (Arabic)",
      english: "الإنجليزية (English)",
      default_currency: "العملة الافتراضية",
      working_day: "يوم عمل",
      holiday: "يوم عطلة",
      add_period: "إضافة فترة",
      working_hours_note: "سيتم تطبيق هذه الأوقات على نظام المواعيد والحجز",
      email_error: "يرجى إدخال بريد إلكتروني صحيح",
      phone_number_error: "يرجى إدخال رقم هاتف صحيح (8 أرقام على الأقل)",
      save_settings: "حفظ الإعدادات",
      cancel_changes: "إلغاء التغييرات",
      cancel_confirm_msg: "هل أنت متأكد من إلغاء كافة التغييرات؟ لن يتم حفظ أي تعديلات أجريتها.",
      cancel_btn: "تجاهل التغييرات",
      back_btn: "العودة للتعديل",
      select_currency: "اختر العملة",
      jod: "دينار أردني (د.أ)",
      usd: "دولار أمريكي (USD)",
    }
  },
  en: {
    settings: {
      settings: "System Settings",
      manage_settings: "Manage clinic settings, working hours, and general options",
      clinic_info: "Clinic Information",
      clinic_info_desc: "Update basic clinic data such as name, phone, and address",
      general_settings: "General Settings",
      general_settings_desc: "Modify system preferences, language, and default currency",
      working_hours: "Working Hours",
      working_hours_desc: "Define daily working periods for each day of the week",
      language: "Language",
      select_language: "Select system language",
      arabic: "Arabic (العربية)",
      english: "English (الإنجليزية)",
      default_currency: "Default Currency",
      working_day: "Working Day",
      holiday: "Holiday",
      add_period: "Add Period",
      working_hours_note: "These times will be applied to the appointment and booking system",
      email_error: "Please enter a valid email address",
      phone_number_error: "Please enter a valid phone number (at least 8 digits)",
      save_settings: "Save Settings",
      cancel_changes: "Cancel Changes",
      cancel_confirm_msg: "Are you sure you want to cancel all changes? none of your modifications will be saved.",
      cancel_btn: "Discard Changes",
      back_btn: "Back to Editing",
      select_currency: "Select Currency",
      jod: "Jordanian Dinar (JOD)",
      usd: "US Dollar (USD)",
    }
  }
};
